---
title: "Practice Activity 9.2"
author: "Chloe Feehan"
format:
  html: 
    self-contained: true
    code-tools: true
    code-fold: true
execute:
  echo: true
  error: true
  message: false
  warning: false
---

```{r}
library(tidyverse)
```

What is the 95th percentile for trumpet weight?
```{r}
qunif(.95, min = 1.5, max = 3.5)
```

What is the 10th percentile for trombone weight?
```{r}
qnorm(.1, mean = 4.6, sd = 0.8)
```

About what percent of trombones do you expect to be more than 5 pounds?
```{r}
dnorm(5, mean = 4.6, sd = 0.8)
```

About what percent of reed instruments do you expect to be more than 5 pounds?
```{r}
dchisq(5, df = 4)
```

Simulate 100 random trombone weights. How many of them were below 4 pounds?

```{r}
rnorm(100, mean = 4.6, sd = .8) 

sum((rnorm(100, mean = 4.6, sd = .8)) < 4)

```

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = .8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(c(trombones, cornets, reeds)))
  
}

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                      ) 

sum(my_weights < 4532)

```



#saxophones, clarinets, bassoons = reed instruments