---
title: "Practice Activity 4: Tidy Data with tidyr"
author: "Chloe Feehan"
format:
  html: 
    self-contained: true
    code-tools: true
    code-fold: true
execute:
  echo: true
  error: true
  message: false
  warning: false
---

```{r}
library(readxl) 
library(tidyverse)

military <- read_xlsx(here::here("Practice Activities", "PA 4", 
                                 "gov_spending_per_capita.xlsx"), 
                      sheet = "Share of Govt. spending", 
                      skip = 7, 
                      n_max = 190)


```

```{r}
military_clean <- military |>
  mutate(across(`1988`:`2019`, .fns = na_if, ". ."),
         across(`1988` : `2019`, .fns = na_if, "xxx"),
         across(`1988` : `2019`, as.numeric))
```

```{r}
cont_region <- read_xlsx(here::here("Practice Activities", "PA 4", 
                                 "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

```{r}
military_clean <- military_clean |>
  anti_join(cont_region, by = c("Country" = "Region"))

```

```{r}

military_long <- military_clean |>
  pivot_longer(cols = `1988` : `2019`, names_to = "Year", 
               values_to = "Spending")
```

```{r}

ggplot(data = military_long, mapping = aes(x = Spending, 
                                             y = Year, 
                                             group = Year)) +
  geom_point() +
  geom_boxplot(fill = "lightpink", outlier.shape = NA)

```

```{r}
military_long |>
  slice_max(Spending, n = 2)
```
