---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

When beginning this course, I had no previous knowledge of programming in R. I struggled with building simple visualizations using ggplot and knowing when to use certain functions. However, as I gathered more skills and learned new functions, I have been able to apply those learned skills into each and every one of my assignments. I have practiced writing tidy and efficient code. Now, creating a visualization comes as second nature due. Throughout the course, I have acquired significant programming knowledge and skills that can be used inside and outside of the classroom. Specifically, I have improved upon the Data Visualization, Program Efficiency, and Working with Data learning targets. 

One artifact that I am particularly proud of is Lab 7. In Lab 7, I was able to combine many of the skills I learned throughout the quarter into one assignment. One of the learning targets that was used in almost every lab was Data Visualization and Summarization. Through the repeated practice of building plots, I was able to learn different techniques to make these visualizations more appealing and easier to read. Looking at Question 2.2 in Lab 7, my visualization for the missing fish weight values included a plot title, axis labels, facet colors, facet labels, and a specified font. These are all attributes of tidy visualization that demonstrates my creativity. In previous labs, I conducted external research to figure out how to apply specific colors to the legend. I learned that using the scale_fill_manual function, you can specify colors using the values argument. 

In addition to the Data Visualization and Summarization learning target, Lab 7 also includes the Program Efficiency learning target. In Question 3 (Part Two), I wrote a function that rescales the data. Inside the rescale function, I used the range function and called the first and second values of the output in order to get the minimum and maximum values to calculate the rescaled value. This demonstrates concise code that doesn’t repeat itself as well as uses a function to reduce repetition and potential sources of error. 

The Working with Data learning target is applied throughout the lab, beginning with importing data from a csv format using the here package. I also demonstrated my ability to modify and summarize variables through Question 3.5. I used the mutate function in combination with the across function to apply the function I wrote to the specified columns. In addition, to create the visualization of the missing data in Question 2.2, I filtered the data so that it would only use the NA values, demonstrating another learning target.

In all of the areas in Lab 7 I mentioned, I applied the learning target of Reproducibility. With the additional modifications I made to my plots, I was able to produce professional looking documents as well as tidy and efficient code that uses new lines and spaces when necessary. The functions also make the program resistant to changes, satisfying another aspect of the Reproducibility learning target. 

Although I didn’t include every single learning target in this lab, I feel as though this lab demonstrated many of them. Looking back to the beginning of the course, my visualizations were very basic and didn’t include many modifications. However, as I acquired more skills, I learned how to use piping methods to filter and mutate the dataset so that it would include certain parts of the data in my visualizations as well as modifications to make the plot easier to read. 
